CON_ADDRESS = '127.0.0.1'
CON_PORT = 19999
TIMEOUT_IN_MS = 5000
COMM_THREAD_CYCLE_IN_MS = 5
ROBOTS_NAMES_TREE = 'startConfigurations'
TARGETS_NAMES_TREE = 'goalConfigurations'
OBSTACLES_NAMES_TREE = 'OuterWalls'
WITH_DYNAMIC_OBSTACLES = False